### ISSUE TITLE
The predicted scores are not correct

### ISSUE THREAD

**Issue by sathishkumark27** [aimerykong/deepImageAestheticsAnalysis#24]
Hi, Thanks for sharing the pre-trained models.
I am using the init model and when I try to predict the scores for below images the scores are not correct  
**image -1 :**
![7237532 14_frame3467](https://user-images.githubusercontent.com/31283567/65202190-0436b600-da3f-11e9-940f-962887c67828.png)
`Scores :  
{'fc11_score': array([[0.7237532]], dtype=float32), 'fc9_MotionBlur': array([[-0.00683291]], dtype=float32), 'fc9_Repetition': array([[0.1499309]], dtype=float32), 'fc9_ColorHarmony': array([[0.41779417]], dtype=float32), 'fc9_Light': array([[0.23401856]], dtype=float32), 'fc9_Content': array([[0.44104707]], dtype=float32), 'fc9_Object': array([[0.15831222]], dtype=float32), 'fc9_BalancingElement': array([[0.08793019]], dtype=float32), 'fc9_Symmetry': array([[0.05824818]], dtype=float32), 'fc9_RuleOfThirds': array([[0.2551845]], dtype=float32), 'fc9_DoF': array([[0.14344457]], dtype=float32), 'fc9_VividColor': array([[0.20968038]], dtype=float32)}
./frame3467.png 	 0.7237532`

**Image -2** 
![6647498 61_frame2742](https://user-images.githubusercontent.com/31283567/65202419-32b49100-da3f-11e9-9567-f43aad301d6d.png)
`Scores : 
{'fc11_score': array([[0.66474986]], dtype=float32), 'fc9_MotionBlur': array([[-0.00710997]], dtype=float32), 'fc9_Repetition': array([[0.11318572]], dtype=float32), 'fc9_ColorHarmony': array([[0.3682373]], dtype=float32), 'fc9_Light': array([[0.19498739]], dtype=float32), 'fc9_Content': array([[0.52042776]], dtype=float32), 'fc9_Object': array([[0.13005672]], dtype=float32), 'fc9_BalancingElement': array([[0.04698427]], dtype=float32), 'fc9_Symmetry': array([[0.13396302]], dtype=float32), 'fc9_RuleOfThirds': array([[0.23525675]], dtype=float32), 'fc9_DoF': array([[0.17191094]], dtype=float32), 'fc9_VividColor': array([[0.11277764]], dtype=float32)}
./frame2742.png 	 0.66474986`

By looking at those 2 images it is evident that Image -1 is better than Image-2 but the predictions are suggesting otherwise, can you please help to understand the issue?

**Comment by aimerykong** [comment]
Hi, thanks for your interest and trying this!
The failure results are not too surprising to me. My explanation is that,
the model is trained and test on the same image statistics. But here you
provide the model with an image which has much artifact, different from the
training images. So the model fails easily. This also indicates the limited
generalizability of the model.

Hope this helps!
Shu

**Comment by sathishkumark27** [comment]
Okay got it, thank you.
