### ISSUE TITLE
Track each rating from different rater

### ISSUE THREAD

**Issue by junjzhang** [aimerykong/deepImageAestheticsAnalysis#29]
I notice that each image is based on rating from five raters, will it be possible to get these original rating scores? Or will it be possible to track each raters' rating score？

**Comment by aimerykong** [comment]
Hi, the files of your interest are in the [google drive repository](https://drive.google.com/drive/folders/0BxeylfSgpk1MOVduWGxyVlJFUHM?usp=sharing), a file named "[allinAll.csv](https://drive.google.com/file/d/0BxeylfSgpk1MQ0hQaVJmQ0R3dU0/view?usp=sharing)", and "[result_csv.csv](https://drive.google.com/file/d/0BxeylfSgpk1MaXQ3WlVHRk40RXc/view?usp=sharing)". Please check both.

**Comment by junjzhang** [comment]
Thank you very much!
