### ISSUE TITLE
How to reproduce ?

### ISSUE THREAD

**Issue by trancept** [aimerykong/deepImageAestheticsAnalysis#3]
Hello,
I've made a Python script to use your model :
https://github.com/trancept/deepImageAestheticsAnalysis/blob/master/python/caffe_prediction.py
I use imagenet_mean.binaryproto + initNetArch.deploy + initModel_iter_16000.caffemodel , is it the right combination of file ?

Te code execute without error and produce results :

```
/Datasets/AVA/farm1_255_19591276064_e10b2b4791_b.jpg
{'fc12_weightedSum': array([[ 0.51903391]], dtype=float32)}

/Datasets/AVA/farm1_256_19798733389_c483edcd95_b.jpg
{'fc12_weightedSum': array([[ 0.45865908]], dtype=float32)}
```

But not sure we could say that it works as expected because I will not have ordered the aesthetic quality the same way.

Thank you for sharing

**Comment by aimerykong** [comment]
Hi, Benoit,

Thank you for trying our code.

My matlab file reads "initModel.prototxt", 'initModel.caffemodel' and
'mean_AADB_regression_warp256.binaryproto'. So I'd suggest you use these
files to see if you still get the error. These files can be downloaded
through ( https://drive.google.com/open?id=0BxeylfSgpk1MOVduWGxyVlJFUHM )

Please let me know if this works.

Thanks!

Regards,
Shu
weightsName = 'initModel';
model = ['./initModel', weightsName, '.prototxt'];
weights = ['./initModel', weightsName, '.caffemodel'];
if ~exist('net', 'var')
net = caffe.Net(model, weights, 'test');
end
meanImg = './mean_AADB_regression_warp256.binaryproto';
meanImg = caffe.io.read_mean(meanImg);

https://github.com/aimerykong/deepImageAestheticsAnalysis/
blob/master/demoRatingImages/main_demo4_suggestion.m

**Comment by trancept** [comment]
Thank you, now I have this output:
`{'fc9_ColorHarmony': array([[-0.02013153]], dtype=float32), 'fc9_MotionBlur': array([[-0.09567797]], dtype=float32), 'fc9_Light': array([[-0.13579112]], dtype=float32), 'fc9_Content': array([[-0.03879307]], dtype=float32), 'fc9_Repetition': array([[ 0.16459915]], dtype=float32), 'fc11_score': array([[ 0.44403398]], dtype=float32), 'fc9_DoF': array([[ 0.02668561]], dtype=float32), 'fc9_VividColor': array([[-0.03753702]], dtype=float32), 'fc9_Symmetry': array([[ 0.0518541]], dtype=float32), 'fc9_Object': array([[-0.10494429]], dtype=float32), 'fc9_BalancingElement': array([[-0.0258556]], dtype=float32), 'fc9_RuleOfThirds': array([[-0.05445363]], dtype=float32)}`

**Comment by aimerykong** [comment]
Great! I'll merge your code so that other people can use both.

Regards,
Shu
