### ISSUE TITLE
how to boost single image process?

### ISSUE THREAD

**Issue by shinebay** [aimerykong/deepImageAestheticsAnalysis#5]
I am a newbie of caffe, I test the code and find that every time loading the caffemodel and handle single image it will takes about 19 seconds, so  is there any way to boost single image process? Also, a silly question for newbie: how can I use python to  train the model?thanks

**Comment by aimerykong** [comment]
If you use gpu using --
          caffe.set_mode_gpu() 
then it can be much faster.

As for training using python, please refer to
http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb
http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/01-learning-lenet.ipynb
http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/02-fine-tuning.ipynb
