### ISSUE TITLE
can deepImageAestheticsAnalysis python code apply to ILGnet?

### ISSUE THREAD

**Issue by shinebay** [aimerykong/deepImageAestheticsAnalysis#6]
I find this project: https://github.com/BestiVictory/ILGnet , you can test it. They declare their test results shows very well, 85.50% accuracy:
http://jinxin.me/downloads/pics/WCSP2016-Classification.jpg
it uses AVA datasets instead of AADB, so how can I change your project python code: caffe_prediction.py to apply to the ILGnet? thank you very much

**Comment by aimerykong** [comment]
Cool! The improved performance might be due to deeper network (inception net). I'm not sure how to modify the python code to train it using caffe. The python code is written by others. I use scripts to train it directly.
