### ISSUE TITLE
Is the "fc11_score" the result score to check an image is nice or not?

### ISSUE THREAD

**Issue by shinebay** [aimerykong/deepImageAestheticsAnalysis#7]
deepImageAestheticsAnalysis provide 'BalacingElements', 'ColorHarmony', 'Content', 'DoF', 'Light', 'MotionBlur', 'Object', 'Repetition', 'RuleOfThirds', 'Symmetry', 'VividColor' factors for every image, but the sum of these values are NOT equal to the fc11_score, I just wonder what the fc11_score is ? it is the only result score aesthetic of an image? thank you

**Comment by aimerykong** [comment]
I guess you are looking at the "initModel". This model combines attribute
features and a base feature (fc8) for the final prediction (fc11_score). So
it does not make sense to sum up the attribute scores (which should be the
attribute classification). fc11_score is the only prediction in this model.
