### ISSUE TITLE
A question about how to train?

### ISSUE THREAD

**Issue by guoxiaolu** [aimerykong/deepImageAestheticsAnalysis#9]
Good and impressive job! I have check your train prototxt (using siamese network) and try to train your network. But I find it is different from predicted prototxt of initModel. And I'm confused with your paper given 3 architectures and two given prototxt. Can you give more information of train detail?

**Comment by aimerykong** [comment]
Hi,

Thank you for your interest!

The matlab file reads "initModel.prototxt", 'initModel.caffemodel' and
'mean_AADB_regression_warp256.binaryproto'. These files can be downloaded
through ( https://drive.google.com/open?id=0BxeylfSgpk1MOVduWGxyVlJFUHM)

The model "initModel" combines attribute features and a base feature (fc8)
for the final prediction (fc11_score). So it does not make sense to sum up
the attribute scores (which should be the attribute classification).
fc11_score is the only prediction in this model.

The model released is not the straightforward starting model. I train all
the models in stages. First, I train regression model as the start-point
model, then add rank loss, later add attribute branches and finally
content. I insert rank loss in the last two stages also to analyze more on
the experiments. Well, I can't remember which models are corresponding to
the models released in google drive :(

Hope this helps.

Regards,
Shu

**Comment by guoxiaolu** [comment]
Thank you very much, I will check it~
